### ISSUE TITLE
Cannot update plugins inside webUI

### ISSUE THREAD

**Issue by MotorBottle** [k7212519/ksd-launcher#1]
I tried to update controlnet and other plugins inside webui but got err messages.

**Comment by MotorBottle** [comment]
And then the WebUI won't load and run anymore if I try to update plugins inside WebUI. Need to clean reinstall.

**Comment by k7212519** [comment]
If there is GFW in your area, please use a proxy software such as the Linux version of " Clash for Windows ". After setting it up, select "Tools" in the ksd-launcher menu to "Proxy Address Settings," and enter the address of the proxy software. If you are using Clash, the address is http://127.0.0.1:7890. It is normal for the installation process to be stuck at "installing requirements ……" after updating, so please be patient. If you encounter other errors, please provide the error message detail. For some common issues, please refer to this article at https://b23.tv/JT8JAmV.

**Comment by MotorBottle** [comment]
Thanks and for my case need to set https proxy. But it’s solved anyway. FYI I’m using electron ssr not clash, might be this cause

**Comment by MotorBottle** [comment]
After all, problem solved, thanks again
