### ISSUE TITLE
如何让局域网内的别的设备也能访问7890端口。

### ISSUE THREAD

**Issue by m0eak** [k7212519/ksd-launcher#2]
输入ip:7890无法打开webui，docker改如何设置啊。

**Comment by k7212519** [comment]
需要在启动参数里添加 --listen 参数，才会开启端口监听。docker已经做了端口映射，和docker无关。

**Comment by m0eak** [comment]
好的谢谢，我去试一下--发自新浪邮箱客户端
在 6月17日 13:48，k7212519 ***@***.***> 写道：

需要在启动参数里添加 --listen 参数，才会开启端口监听。docker已经做了端口映射，和docker无关。

&mdash;
